services:
  backend:
    build: ./infra/docker/php
    container_name: backend
    volumes:
      - ./backend:/var/www/html
  frontend:
    image: node:20-alpine
    container_name: front
    volumes:
      - ./front:/app
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
      - "5173:5173"
  nginx:
    build: ./infra/docker/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/:/var/www/html
      - ./infra/docker/nginx:/etc/nginx/conf.d
      - cert-data:/etc/letsencrypt
      - ./infra/docker/nginx/html:/var/www/html/cert-check
    depends_on:
      - backend
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - cert-data:/etc/letsencrypt
      - ./infra/docker/nginx/html:/var/www/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12d & wait $${!}; done;'"

volumes:
  cert-data:
  dbdata:
