# server {
#     listen 80;
#     server_name www.squreation.com;

#     # ★ここを修正
#     location ^~ /.well-known/acme-challenge/ {
#         root /var/www/html;
#         allow all;
#         default_type "text/plain";
#     }

#     location / {
#         return 301 https://$host$request_uri;
#     }
# }

# server {
#     listen 443 ssl;
#     server_name www.squreation.com;

#     ssl_certificate     /etc/letsencrypt/live/://squreation.com;
#     ssl_certificate_key /etc/letsencrypt/live/://squreation.com;

#     root /var/www/html/public;
#     index index.php index.html;

#     location / {
#         try_files $uri $uri/ /index.php?$query_string;
#     }

#     location ~ \.php$ {
#         fastcgi_pass php:9000;
#         fastcgi_index index.php;
#         include fastcgi_params;
#         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#         fastcgi_param HTTPS on; # LaravelのAsset(CSS/JS)がhttpにならないよう強制
#     }
# }

server {
    listen 80;
    server_name www.squreation.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
        allow all;
        default_type "text/plain";
    }

    # 証明書が取れるまではHTTPSリダイレクトをコメントアウト
    location / {
        root /var/www/html/public;
        index index.php index.html;
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHPの設定もここに一時的に移動（認証用）
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
    }
}
