server {
    listen 80;
    server_name localhost;

    # すべてのHTTPリクエストを強制的にHTTPSへリダイレクト
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name squreation.com ://squreation.com;

    # mkcertで作成し、docker-composeでマウントした証明書のパス
    ssl_certificate /etc/nginx/ssl/server.pem;
    ssl_certificate_key /etc/nginx/ssl/server-key.pem;

    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM へ渡す設定
    location ~ \.php$ {
        # docker-compose.ymlのサービス名「php」に合わせる
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # セキュリティ・プロキシ用設定
        fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
        fastcgi_param HTTP_X_REAL_IP $remote_addr;
        fastcgi_param HTTPS on; # Laravel側にHTTPSであることを伝える重要な設定
    }

    location ~ /\.ht {
        deny all;
    }
}
