server {
    listen 80;
    server_name www.squreation.com; # ドメイン名は適宜修正してください

    # Certbotのドメイン認証（ACMEチャレンジ）用
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    # すべてのHTTPリクエストをHTTPSへリダイレクト
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name www.squreation.com;

    # Let's Encryptで生成されるパスを指定
    ssl_certificate /etc/letsencrypt/live/://squreation.com;
    ssl_certificate_key /etc/letsencrypt/live/://squreation.com;

    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS on; # LaravelのAsset(CSS/JS)がhttpにならないよう強制
    }
}
